# AWS playbook
---

- hosts: localhost
  connection: local
  gather_facts: False
  vars: 
    keypair_name: "Master-01"
    region: "ap-southeast-1"
    zone: "ap-southeast-1a"
    vpc_name: "Ansible VPC"
    vpc_cidr: 10.10.0.0/24
    subnet_name: "AnsibleSubnet"
    subnet_cidr: 10.10.0.0/26
    igw_name: "IGW"
    securitygroup_name: "AnsibleSg"
    ec2_tag: "WebServer"
  tasks:
         
    - name: create VPC
      ec2_vpc_net:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ region }}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: present
      register: ec2_vpc

    - name: create IGW
      ec2_vpc_igw:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        vpc_id: "{{ ec2_vpc.vpc.id }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: "{{ igw_name }}"
      register: igw_result

    - name: Create ec2 vpc subnet
      ec2_vpc_subnet:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        vpc_id: "{{ ec2_vpc.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone }}"
        state: present
        cidr: "{{ subnet_cidr }}"
        map_public: yes
        resource_tags:
          Name: "{{ subnet_name }}"
      register: subnet_result

    - name: Route 
      ec2_vpc_route_table:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        vpc_id: "{{ ec2_vpc.vpc.id }}"
        region: "{{ region }}"
        state: present
        subnets:
          - "{{ subnet_result.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_result.gateway_id  }}"
      register: public_route_table



    - name: Create Security Group
      ec2_group:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_access_key }}"
        name: Web
        description: Web Security Group
        vpc_id: "{{ ec2_vpc.vpc.id }}"
        region: "{{ region }}"
        state: "present"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22
      register: security_group_result

    - name: Create EC2 server
      ec2:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        image: ami-0f7719e8b7ba25c61
        wait: yes
        instance_type: t2.micro
        region: "{{ region }}"
        group_id: "{{ security_group_result.group_id }}"
        vpc_subnet_id: "{{ subnet_result.subnet.id }}"
        key_name: "{{ keypair_name }}"
        count_tag:
          Name: Webserver
        exact_count: 1
        
    - name: Facts
      block:

      - name: Get instances facts
        ec2_instance_facts:
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          region: "{{ region }}"
        register: result

      - name: Instances ID
        debug:
          msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
        loop: "{{ result.instances }}"
      